name: First Workflow
on: [push]

jobs:

  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: show env vars
        run: env
      - name: Multiline Command
        run: |
          node -v
          npm -v
          python3 --version
          gh --version
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: show env vars
        run: env
      - name: View SW Version
        run: sw_vers
      - name: Multiline Command
        run: |
          node -v
          npm -v
          python3 --version
          gh --version

  dependant-job:

    runs-on: ${{vars.W_RUNNER}}
    needs: [run-shell-commands]
    steps:
      - name: show env vars
        run: env
      - name: Multiline Command
        run: |
          node -v
          npm -v
          python3 --version
          gh --version
