name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v
          python3 --version

      - name: install gh
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && sudo mkdir -p -m 755 /etc/apt/sources.list.d \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y        


  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
      - name: Multiline Command
        run: |
          node -v
          npm -v
          python3 --version
      - name: install gh
        run: |
          brew install gh
  dependant-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Multiline Command
        run: |
          node -v
          npm -v
          python3 --version
      - name: install gh
        run: |
          winget install --id GitHub.cli
