name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message
        run: echo "::error title:Error title, file=app.js, line=2, endLine=3, col=5, endCoumn=7::Missing semicolon"
      - name: Setting a debug message
        run: echo "::debug title:Debug title, file=app.js, line=2, endLine=3, col=5, endCoumn=7::Missing semicolon" 
      - name: Setting an Warning message
        run: echo "::warning title:Error title, file=app.js, line=2, endLine=3, col=5, endCoumn=7::Missing semicolon"
      - name: Setting an Notice message
        run: echo "::notice title:Error title, file=app.js, line=2, endLine=3, col=5, endCoumn=7::Missing semicolon"
  
      - name: Group of logs
        run: |
          echo "::group::My group title"
          echo "Inside group"
          echo "::endgroup::"

      - name: Masking a value
        run: echo "::add-mask::Secret String"
      - name: echo a secret
        run: echo "Secret string"        